export const path = "path"
export const nav_select = "nav_select"
export const nav_select_index = "nav_select_index"
export const animationName = "animationName"
export const animationName_fade = "fade"
export const animationName_translateX = "translateX"
export const animationName_bottom2top = "bottom2top"
